function MeasJW101 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MEASJW101 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  MEASJW101 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jul-2023 08:59:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Name", "Measurement", "LengthMm", "Length2Mm", "Angle", "InnerAngle", "SupplementaryAngle", "OuterAngle", "Greyscale", "P1xMm", "P1yMm", "P1zMm", "P2xMm", "P2yMm", "P2zMm", "P3xMm", "P3yMm", "P3zMm", "P4xMm", "P4yMm", "P4zMm", "Tool", "Time", "File"];
opts.VariableTypes = ["string", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "datetime", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Name", "Measurement", "File"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "Measurement", "LengthMm", "Length2Mm", "Angle", "InnerAngle", "SupplementaryAngle", "OuterAngle", "P2xMm", "P2yMm", "P2zMm", "P3xMm", "P3yMm", "P3zMm", "P4xMm", "P4yMm", "P4zMm", "Tool", "File"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Time", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
MeasJW101 = readtable(filename, opts);

end